export const COMMON_STOCKS = [
  { symbol: 'PETR4', name: 'Petrobras PN' },
  { symbol: 'PETR3', name: 'Petrobras ON' },
  { symbol: 'VALE3', name: 'Vale S.A. ON' },
  { symbol: 'ITUB4', name: 'Itaú Unibanco PN' },
  { symbol: 'BBDC4', name: 'Bradesco PN' },
  { symbol: 'BBDC3', name: 'Bradesco ON' },
  { symbol: 'BBAS3', name: 'Banco do Brasil ON' },
  { symbol: 'ABEV3', name: 'Ambev ON' },
  { symbol: 'MGLU3', name: 'Magazine Luiza ON' },
  { symbol: 'WEGE3', name: 'WEG S.A. ON' },
  { symbol: 'RENT3', name: 'Localiza ON' },
  { symbol: 'B3SA3', name: 'B3 S.A. ON' },
  { symbol: 'SUZB3', name: 'Suzano ON' },
  { symbol: 'JBSS3', name: 'JBS S.A. ON' },
  { symbol: 'RAIL3', name: 'Rumo S.A. ON' },
  { symbol: 'GGBR4', name: 'Gerdau PN' },
  { symbol: 'LREN3', name: 'Lojas Renner ON' },
  { symbol: 'HAPV3', name: 'Hapvida ON' },
  { symbol: 'RADL3', name: 'RaiaDrogasil ON' },
  { symbol: 'CSAN3', name: 'Cosan ON' },
  { symbol: 'VIVT3', name: 'Telefônica Brasil ON' },
  { symbol: 'ELET3', name: 'Eletrobras ON' },
  { symbol: 'ELET6', name: 'Eletrobras PNB' },
  { symbol: 'EQTL3', name: 'Equatorial ON' },
  { symbol: 'PRIO3', name: 'PetroRio ON' },
  { symbol: 'UGPA3', name: 'Ultrapar ON' },
  { symbol: 'RDOR3', name: 'Rede D\'Or ON' },
  { symbol: 'ASAI3', name: 'Assaí ON' },
  { symbol: 'CPLE6', name: 'Copel PNB' },
  { symbol: 'ENEV3', name: 'Eneva ON' },
  { symbol: 'EGIE3', name: 'Engie Brasil ON' },
  { symbol: 'CMIG4', name: 'Cemig PN' },
  { symbol: 'SBSP3', name: 'Sabesp ON' },
  { symbol: 'TIMS3', name: 'TIM Brasil ON' },
  { symbol: 'VBBR3', name: 'Vibra Energia ON' },
  { symbol: 'CSNA3', name: 'Siderúrgica Nacional ON' },
  { symbol: 'GOAU4', name: 'Metalúrgica Gerdau PN' },
  { symbol: 'BRFS3', name: 'BRF S.A. ON' },
  { symbol: 'EMBR3', name: 'Embraer ON' },
  { symbol: 'MULT3', name: 'Multiplan ON' },
  { symbol: 'CYRE3', name: 'Cyrela ON' },
  { symbol: 'MRVE3', name: 'MRV Engenharia ON' },
  { symbol: 'AZUL4', name: 'Azul PN' },
  { symbol: 'GOLL4', name: 'Gol PN' },
  { symbol: 'CVCB3', name: 'CVC Brasil ON' },
  { symbol: 'COGN3', name: 'Cogna ON' },
  { symbol: 'YDUQ3', name: 'Yduqs ON' },
  { symbol: 'BEEF3', name: 'Minerva ON' },
  { symbol: 'BRKM5', name: 'Braskem PNA' },
  { symbol: 'CCRO3', name: 'CCR ON' },
  { symbol: 'CIEL3', name: 'Cielo ON' },
  { symbol: 'CPFE3', name: 'CPFL Energia ON' },
  { symbol: 'CRFB3', name: 'Carrefour Brasil ON' },
  { symbol: 'DXCO3', name: 'Dexco ON' },
  { symbol: 'ECOR3', name: 'EcoRodovias ON' },
  { symbol: 'ENGI11', name: 'Energisa Unit' },
  { symbol: 'EZTC3', name: 'EZTEC ON' },
  { symbol: 'FLRY3', name: 'Fleury ON' },
  { symbol: 'IRBR3', name: 'IRB Brasil ON' },
  { symbol: 'KLBN11', name: 'Klabin Unit' },
  { symbol: 'LWSA3', name: 'Locaweb ON' },
  { symbol: 'PETZ3', name: 'Petz ON' },
  { symbol: 'QUAL3', name: 'Qualicorp ON' },
  { symbol: 'RAIZ4', name: 'Raízen PN' },
  { symbol: 'SANB11', name: 'Santander Brasil Unit' },
  { symbol: 'SLCE3', name: 'SLC Agrícola ON' },
  { symbol: 'SOMA3', name: 'Grupo Soma ON' },
  { symbol: 'TOTS3', name: 'Totvs ON' },
  { symbol: 'USIM5', name: 'Usiminas PNA' },
  { symbol: 'ALPA4', name: 'Alpargatas PN' },
  { symbol: 'ARZZ3', name: 'Arezzo ON' },
  { symbol: 'BPAC11', name: 'BTG Pactual Unit' },
  { symbol: 'BPAN4', name: 'Banco Pan PN' },
  { symbol: 'CASH3', name: 'Méliuz ON' },
  { symbol: 'DIRR3', name: 'Direcional ON' },
  { symbol: 'GRND3', name: 'Grendene ON' },
  { symbol: 'JHSF3', name: 'JHSF ON' },
  { symbol: 'MOVI3', name: 'Movida ON' },
  { symbol: 'ODPV3', name: 'Odontoprev ON' },
  { symbol: 'PSSA3', name: 'Porto Seguro ON' },
  { symbol: 'SMTO3', name: 'São Martinho ON' },
  { symbol: 'STBP3', name: 'Santos Brasil ON' },
  { symbol: 'TRPL4', name: 'ISA CTEEP PN' },
];
